name: PyInstaller Engine Release
on: [ push, pull_request ]

jobs:
  build:

    runs-on: windows-latest

    steps:

      - id: release_drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build with pyinstaller
        run: |
          pyinstaller --onefile engine.spec --version-file=file_version_info.txt
      - name: Test
        run: |
          ls dist/

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v2
        with:
          name: engine.exe
          path: dist/engine.exe

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/engine.exe
          asset_name: engine.exe
          tag: ${{ steps.release_drafter.outputs.tag_name }}
          overwrite: true
  
